import { Link } from "react-router-dom";
import { useEffect } from "react";
import { Brain } from "lucide-react";

export default function TermsPage() {
  useEffect(() => {
    document.title = "Terms of Service — LoanWise AI";
  }, []);

  return (
    <div className="min-h-screen bg-white">
      <header className="border-b px-6 py-4 flex items-center justify-between max-w-5xl mx-auto">
        <Link to="/" className="flex items-center gap-2">
          <div className="h-7 w-7 rounded-md bg-blue-600 flex items-center justify-center">
            <Brain className="h-4 w-4 text-white" />
          </div>
          <span className="font-bold text-slate-900">LoanWise AI</span>
        </Link>
        <Link to="/" className="text-sm text-slate-500 hover:text-slate-900 transition-colors">
          ← Back to Home
        </Link>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16 prose prose-slate prose-sm">
        <h1>Terms of Service</h1>
        <p className="lead">Last updated: March 15, 2026</p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using LoanWise AI, you agree to be bound by these Terms of Service. If you
          do not agree to these terms, please do not use the platform.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          LoanWise AI is a loan application management platform that uses artificial intelligence to
          assist in loan evaluation. It is provided as a demonstration and portfolio project and is
          not a licensed financial institution.
        </p>

        <h2>3. Application and Decisions</h2>
        <p>
          Loan decisions generated by the platform are AI-assisted and are intended for demonstration
          purposes only. They do not constitute actual loan approvals or financial advice.
        </p>

        <h2>4. User Responsibilities</h2>
        <ul>
          <li>You agree to provide accurate and truthful information in your application.</li>
          <li>You are responsible for maintaining the security of your account credentials.</li>
          <li>You agree not to use the platform for any fraudulent or illegal purposes.</li>
        </ul>

        <h2>5. Limitation of Liability</h2>
        <p>
          LoanWise AI is provided "as is" without warranty of any kind. We are not liable for any
          decisions made based on the AI outputs or any losses arising from use of the platform.
        </p>

        <h2>6. Changes to Terms</h2>
        <p>
          We may update these terms at any time. Continued use of the platform after changes
          constitutes acceptance of the new terms.
        </p>

        <h2>7. Contact</h2>
        <p>
          For questions about these terms, contact us at{" "}
          <a href="mailto:legal@loanwise.ai">legal@loanwise.ai</a>.
        </p>
      </main>
    </div>
  );
}
